// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgvxcngpbnbrcdukftnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRndnhjbmdwYm5icmNkdWtmdG54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNjQ1NTcsImV4cCI6MjA2MTk0MDU1N30.M-J8nrJy8tIUhvqg6uEgvFH-6Nj9dOshFbIyBH2YtVk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);